### PR TITLE
#42 - Implement enter a group

### PR DESCRIPTION
**Pull request by ai-mt**

### CODE REVIEW

**Comment by TitanNano** [comment]
@ai-mt how do you guarantee that users don't enter groups before the device is registered?

**Comment by ai-mt** [comment]
@TitanNano I only implemented the function to enter a group with a password. To handle if registered than enter a group, I suggest to do this in the code behind of the LoginView.

**Comment by TitanNano** [comment]
@ai-mt what I mean is that if the use for some reason, is able to enter the code for a group before the device is registered, your API call will fail. 

And please implement everything 😂 the entire user flow.

**Comment by ai-mt** [comment]
ok

**Comment by TitanNano** [comment]
@ai-mt why are you navigating to the question view after entering a group? We don't have any question data.

**Comment by ai-mt** [comment]
So, you don't want the question data loaded when QuestionView is initialized, but rather at the LoginView?

**Comment by TitanNano** [comment]
Well question data is loaded once we get a push. Therefore I don't understand why you want to navigate to the question view. we have nothing to show there...

**Comment by ai-mt** [comment]
ok, so after entering a group I just return a value "isInGroup = true"?

**Comment by TitanNano** [comment]
yes, and you need to display success or failure on the login screen.

**Comment by ai-mt** [comment]
ok, then I'm going to change it.

**Comment by ai-mt** [comment]
Please do not merge, I have to resolve a conflict

**Comment by ai-mt** [comment]
now, everything works

**Review by TitanNano — APPROVED** [review]

**Pull request merged**
