### PR TITLE
#34 - Implement basic navigation

### LINKED ISSUE #34: Implement basic navigation
Implement a basic navigation, so we can use the "continue" buttons to navigate between view. No actual logic just the possibility to navigate from view to view.

### PR DESCRIPTION
**Pull request by xyleninja**
Most basic type of navigation on LoginView Entry "en_pincode".
Can't test it on my Device because "Fragenseite" fails to build.

closes #34

### CODE REVIEW

**Review by TitanNano — CHANGES_REQUESTED** [review]
Please don't instantiate a page when you navigate to it. We want them to be instantiated when the applications starts and then just push them to the navigation.

**Comment by TitanNano** [comment]
- Don't navigate on the ContentPage, use App.Current.MainPage.Navigation to navigate
- don't push modal, push them normally

**Comment by TitanNano** [comment]
sorry, you have to rebase this, I accidentally merged your second PR first.

**Comment by xyleninja** [comment]
it builds and runs. i think the rebase was successful

**Review by TitanNano — APPROVED** [review]

**Pull request merged**
